version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: elasticsearch
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "cluster.name=elk"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.1
    container_name: logstash
    depends_on:
      - elasticsearch
    networks:
      - elk
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline.conf:/usr/share/logstash/pipeline/logstash.conf:ro

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.0.1
    container_name: kibana
    depends_on:
      - elasticsearch
    networks:
      - elk
    ports:
      - "5601:5601"
    environment:
      - "server.name=kibana"
      - "server.host=0"
      - "elasticsearch.hosts=http://elasticsearch:9200"

volumes:
  esdata:

networks:
  elk:
    external:
      name: elk
